### ISSUE TITLE
CTL Roadmap

### ISSUE THREAD

**Issue by epiro-ps** [ArdanaLabs/dUSD#170]
We want to have a browser app supporting the feature-complete set of interactions with [our hello-world validator](https://github.com/ArdanaLabs/dUSD/blob/master/onchain/src/Hello.hs) via [cardano-transaction-library](https://github.com/Plutonomicon/cardano-transaction-lib).

# Tasks

- [x] Set up integration from `onchain` to `offchain`, 
  - [x] #152 
  - [x] #173

- [x] Set up the tooling for running CTL runtime dependencies
  - [x] #163 
  - [x] #150 
    - [x] #159 
    - [x] #161 
    - [x]  #158 
    - [x]  #160 

- [x] Set up `hello-world-api` package for interacting with Hello world contract.
  - [x] Code should be written in Purescript.
  - [x] Code should have CTL as a dependency. 
  - [x] #175
  - [x] `hello-world-api` should have a test suite
    - [x] #176
    - [x] #146 
    - [x] #179
  - [x] #171 
  - [x] #162
  - [x] #178 

- [x] Set up the browser application.
  - [x] #165
  - [x] Application code should be written in Purescript and compiled to Javascript for usage in browser script tags.
  - [x] Application code should depend on the `contract-client-api` detailed above, and use it's functions to support contract interactions.
  - [x] #315
    - [x] The resulting CSS, JS, and Html are minimized, and compatible.
    - [x] Browser console should be clean.
    - [x] There should be no dev tooling in build artifact.
  - [x] Nami wallet should be supported for contract transactions
  - [x] There should be a dev server. #228 
    - [x] An `npm` triggered process should serve the web app when called on local.
    - [x] #228
  - [x] A test suite should be set up for the browser application (#225)
    - [x] There should be a test runner for unit tests.
    - [x] There should be a test runner for Integration tests.
    - [x] There should be a test runner for E2E tests.
      - [x] E2E test suite should load a virtualized browser and assert against programmed interactions. 
  - [x] #225 

- [x] Set up the command-line application.
  - [x] #165
  - [x] #183
  - [x] Application code should be written in Purescript and compiled to Javascript for usage in a NodeJS command-line environment (#203 )
  - [x] Application code should depend on the `hello-world-api` detailed above, and use it's functions to support contract interactions (#203 ).
  - [x] There should be tooling for compiling the source code into a production grade NodeJS command-line executable (#203 )
    - [x] There should be no dev tooling in build artifact.
  - [x] Yubihsm should be used for transaction signing.
    - [x] https://github.com/ArdanaLabs/dUSD/issues/233 
  - [x] A test suite should be set up for the command-line application (#203 )

# Additional Features to Verify
It would be useful to leverage this development effort to produce working examples of the following:
- [x] #166 
- [x] Complex Datum builder

# Proposals
- [ ] https://github.com/ArdanaLabs/dUSD/issues/230

# Documentation
- #172
