### ISSUE TITLE
Hello CTL - YubiHSM Roadmap

### ISSUE THREAD

**Issue by epiro-ps** [ArdanaLabs/dUSD#290]
The following needs to be complete in order to support signing CTL transactions with the YubiHSM plugged into the Ardana tenant hardware.
- [x] https://github.com/ArdanaLabs/dUSD/issues/281
- [x] https://github.com/ArdanaLabs/dUSD/issues/233
- [x] https://github.com/ArdanaLabs/yubihsm-ed-sign/issues/20
- [x] https://github.com/ArdanaLabs/dUSD/issues/369
- [x] https://github.com/ArdanaLabs/dUSD/issues/288
